name: Docker Build and Push Image

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get latest code-server version
        id: get_version
        run: |
          VERSION=$(curl -sX GET https://api.github.com/repos/coder/code-server/releases/latest \
            | awk '/tag_name/{print $4;exit}' FS='[""]' | sed 's|^v||')
          echo "::set-output name=version::$VERSION"
      
      - name: Build and push amd64 image
        uses: docker/build-push-action@v2
        with:
          file: ./amd64/Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            kimlulz/alpine-code-server:${{ steps.get_version.outputs.version }}-amd64
            kimlulz/alpine-code-server:latest

      - name: Build and push arm64v8 image
        uses: docker/build-push-action@v2
        with:
          file: ./arm64v8/Dockerfile
          context: .
          platforms: linux/arm64
          push: true
          tags: kimlulz/alpine-code-server:${{ steps.get_version.outputs.version }}-arm64v8
